/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  card: {
    marginTop: 50,
    position: 'relative',
    backgroundColor: '#FFF',
    width: 160,
    height: 240,
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderRadius: 30,
    marginHorizontal: 10,
    // justifyContent: 'center',
    alignContent: 'center',
  },
  imageCard: {
    width: 130,
    height: 130,
    // borderRadius: 20,
  },
  containerImage: {
    width: 130,
    height: 130,
    // borderWidth: 2,
    position: 'relative',
    left: '9%',
    top: -35,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 40,
  },
  containerPromo: {
    position: 'absolute',
    backgroundColor: 'white',
    right: 10,
    top: 1,
    borderRadius: 20,
    width: '50%',
    display: 'flex',
    alignItems: 'center',
  },
  containerTitle: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    top: -10,
  },
  cardTitle: {
    fontFamily: 'Poppins-Bold',
    // fontWeight: 'bold',
    fontSize: 19,
    color: 'black',
    textAlign: 'center',
    width: '70%',
    lineHeight: 22.29,
  },
  cardPrice: {
    fontFamily: 'Poppins-Bold',
    position: 'absolute',
    top: 40,
    // fontWeight: 'bold',
    fontSize: 17,
    color: 'grey',
    textDecorationLine: 'line-through',
  },
  cardPrice2: {
    fontFamily: 'Poppins-Bold',
    position: 'absolute',
    top: 70,
    fontWeight: 'bold',
    fontSize: 17,
    color: '#6A4029',
  },
  textPromo: {
    fontFamily: 'Poppins-Reguler',
    color: 'black',
    fontWeight: '700',
    fontSize: 30,
  },
  conPencl: {
    backgroundColor: '#6A4029',
    width: 55,
    height: 55,
    borderRadius: 100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: -8,
    top: 60,
    borderColor: 'white',
    borderWidth: 2,
  },
  pencil: {
    color: 'white',
  },
});

export default styles;
