/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  navbar: {
    backgroundColor: '#EEEEEE',
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  containerSearch: {
    width: '90%',
    alignSelf: 'center',
    backgroundColor: '#EFEEEE',
    marginTop: 20,
    borderRadius: 50,
    position: 'relative',
    flexDirection: 'row',
  },
  borderSearch: {
    borderWidth: 2,
  },
  inputSearch: {
    width: '90%',
    fontSize: 17,
    paddingHorizontal: 70,
    paddingVertical: 15,
    fontWeight: '900',
    borderRadius: 50,
  },
  searchIcon: {
    width: 30,
    height: 30,
    position: 'absolute',
    top: '24%',
    left: '8%',
  },
  categories: {
    // marginTop: ,
    minWidth: '100%',
    flexDirection: 'row',
    height: 70,
    overflow: 'scroll',
    // borderWidth: 1,
    // paddingRight: 40,
  },
  categoriesTitle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 20,
  },
  categoriesText: {
    fontSize: 17,
  },
  textActive: {
    color: '#6A4029',
    fontWeight: '900',
    borderBottomWidth: 2,
  },
  icon: {
    color: 'black',
    // fontSize: 22,
    fontWeight: '800',
  },
  textNavbar: {
    color: 'black',
    fontSize: 22,
    fontWeight: '800',
    marginLeft: 20,
  },
  scrolles: {
    flex: 1,
    backgroundColor: '#F9F9F9',
    paddingBottom: 15,
  },
  icons: {
    marginRight: 30,
    color: 'black',
    fontSize: 25,
  },
  titleNavbar: {
    fontFamily: 'Poppins-Black',
    fontWeight: 'bold',
    color: 'black',
    fontSize: 17,
  },
  category: {
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
    fontSize: 28,
    color: 'black',
    textAlign: 'center',
    paddingTop: 25,
  },
  category2: {
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
    fontSize: 28,
    marginLeft: 40,
    color: 'black',
    paddingTop: 25,
  },
  containerCard: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    // justifyContent: 'center',
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 25,
    // gap: 25,
    marginHorizontal: 20,
    minHeight: 200,
  },
  card: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#3939391A',
    elevation: 1,
    width: 180,
    height: 212.41,
    borderRadius: 30,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    marginVertical: 30,
  },
  imgProduct: {
    width: 128.98,
    height: 128.98,
    borderRadius: 250,
    position: 'absolute',
    top: -35,
  },
  titleFood: {
    fontFamily: 'Poppins-Black',
    fontWeight: 'bold',
    fontSize: 22,
    textAlign: 'center',
    paddingTop: 90,
    // width: 116,
    lineHeight: 25,
    color: 'black',
  },
  priceFood: {
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
    fontSize: 17,
    color: '#6A4029',
    textAlign: 'center',
  },
  cardContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingTop: 16,
    paddingBottom: 8,
    gap: 14,
  },
  filter: {
    backgroundColor: '#BABABA59',
    paddingHorizontal: 20,
    paddingBottom: 10,
    paddingTop: 10,
    borderRadius: 5,
    fontFamily: 'Poppins-SemiBold',
    color: 'black',
    textAlign: 'center',
    width: 130,
    marginLeft: 230,
    marginTop: 20,
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#787777',
    // paddingVertical: 90,
    // padding: 10,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: 300,
    height: 250,
    justifyContent: 'center',
    gap: 10,
  },
  titleFilter: {
    fontFamily: 'Poppins-Bold',
    color: 'black',
    fontSize: 17,
  },
  buttonFilter: {
    marginHorizontal: 5,
    marginVertical: 5,
    backgroundColor: '#6A4029',
    color: 'white',
    paddingTop: 5,
    paddingBottom: 3,
    paddingHorizontal: 10,
    borderRadius: 5,
    fontFamily: 'Poppins-Bold',
  },
  button: {
    marginHorizontal: 5,
    marginVertical: 5,
    backgroundColor: '#BABABA59',
    color: '#9F9F9F',
    paddingTop: 5,
    paddingBottom: 3,
    paddingHorizontal: 10,
    borderRadius: 5,
    fontFamily: 'Poppins-Bold',
  },
  inputContainer: {
    flexDirection: 'row',
    paddingTop: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    alignItems: 'center',

    // backgroundColor: 'red',
  },
  notFound: {
    textAlign: 'center',
    paddingTop: 90,
    fontFamily: 'Poppins-Bold',
    fontSize: 20,
  },
  act: {
    marginTop: 150,
  },
  // loading: {
  //   width: '100%',
  //   height: '50%',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
});

export default styles;
