/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  sectionContainer: {
    flex: 1,
    paddingBottom: 0,
    // paddingBottom: 54,
  },
  container: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 31,
    paddingTop: 54,
  },
  rightHeader: {
    display: 'flex',
    flexDirection: 'row',
    gap: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  vector: {
    height: 28,
    width: 28,
  },
  pp: {
    height: 33,
    width: 33,
    borderRadius: 110 / 2,
  },
  text: {
    fontFamily: 'Poppins-Bold',
    fontSize: 36,
    marginTop: 24,
    color: 'black',
    paddingHorizontal: 31,
  },
  favorite: {
    color: '#9A9A9D',
    fontFamily: 'Poppins-Bold',
    fontSize: 18,
    display: 'flex',
    // paddingRight: 37,
  },
  list: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 24,
    width: '92%',
    gap: 10,
    paddingHorizontal: 31,
  },
  see: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: '#6A4029',
    width: '100%',
    textAlign: 'right',
    paddingHorizontal: 31,
    marginTop: 15,
    marginBottom: 10,
  },
  loading: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  act: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginLeft: 180,
    paddingBottom: 100,
  },
  searchInput: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '85%',
    borderWidth: 1,
    paddingHorizontal: 30,
    marginHorizontal: 31,
    gap: 10,
    borderRadius: 20,
    backgroundColor: '#EEEEEE',
    marginVertical: 10,
    borderColor: '#9A9A9D',
  },
  notFound: {
    fontFamily: 'Poppins-Bold',
    justifyContent: 'center',
    textAlign: 'center',
    width: '100%',
    paddingLeft: 150,
    paddingTop: 80,
  },
  textActive: {
    color: '#6A4029',
    fontFamily: 'Poppins-Bold',
    borderBottomWidth: 2,
    // width: 83,
  },
  wrapList: {
    // width: 120,
    flex: 1,
    marginHorizontal: 20,
  },
  addCircle: {
    position: 'absolute',
    bottom: 0,
    fontSize: 80,
    right: 300,
    // marginHorizontal: 3,
    color: '#6A4029',
    backgroundColor: 'white',
    borderRadius: 500,
    // width: 'min-content',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  wrappAdd: {
    position: 'relative',
    justifyContent: 'center',
    // alignItems: 'center',
  },
  button: {
    borderRadius: 10,
    width: 200,
    // marginHorizontal: 10,
    marginVertical: 10,
    padding: 10,
    paddingVertical: 20,
    elevation: 2,
  },
  buttonClose: {
    backgroundColor: '#FFBA33',
  },
  textStyle: {
    color: '#6A4029',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    fontFamily: 'Poppins-Bold',
    width: 200,
    color: 'black',
    fontSize: 25,
    marginBottom: 15,
    textAlign: 'center',
  },
  removeCircle: {
    fontSize: 80,
    marginHorizontal: 5,
    marginVertical: 20,
    color: '#FFBA33',
    backgroundColor: 'transparent',
    borderRadius: 300,
  },
  boxX: {
    marginRight: 87,
    marginBottom: 2,
  },
});

export default styles;
